### ISSUE TITLE
spring info is missing / org qs

### ISSUE THREAD

**Issue by ofZach** [SFPC/finance-and-administration#2]
might be good to have spring info up, and also I'm not sure about the library pages, maybe that can be it's own repo?  feels less useful then the finanical info and it's better if all that is in one place.

**Comment by caseyg** [comment]
Working on it!! Sorry it's super late. Wanted to come up with a process to get information out faster and ended up being slower than last time.

Maybe I can post the CSVs and add context as its ready. Wanted to get the draft to a state where I could ask for permission, and then circulate it amongst teachers, then amongst the school and visitors, then make it public, since there was (justified) pushback last time about publishing this info without asking explicitly in advance.

Ultimately think Finance would be more accessible as be a page on the site instead of a separate repo.

Agree on the library stuff, too. In some ways I saw this repo as a place to put any docs relevant to admin or finance, e.g. participant agreement, inventory of our boxes, financial statements. Could explain it better for sure.

**Comment by ofZach** [comment]
I think you should post up CSVs or whatever you have right now for this...

**Comment by caseyg** [comment]
Posted everything by quarter and year since Q3 2013, exported from Xero as PDF and XSLX, and additionally saved as CSV via Xero's Google Docs export.
